name: Terrapin Package Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
      name: Checkout source

    - name: Build package with Oryx
      run:  docker run --volume $(pwd):/repo --volume /home/runner/outputfolder:/output mcr.microsoft.com/oryx/build:latest oryx build --package /repo --output /output -p registry=http://terrapin-dev-worker.azurewebsites.net/api/registry

    - uses: jikuma/githubaction@v0.3.3-alpha
      name: Create release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Terrapin release'
        release_note: 'Job: 9ea5dc31-f9b7-4e30-9432-8926fb03d087 | Package: @11ty/eleventy@0.8.3 | Manager: Npm | Commit: ${{ github.sha }}'
        asset_filepath: '/home/runner/outputfolder/@11ty/eleventy-0.8.3.tgz'
        tag_name: v0.8.3+${{ github.sha }}
